### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by talagluck**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by xhochy — CHANGES_REQUESTED** [review]
Please edit the `meta.yaml`

**Comment by talagluck** [comment]
Done - thanks!

**Comment by xhochy** [comment]
No, you also need to rerender

**Comment by xhochy** [comment]
@talagluck This is quite offensive to merge PRs when there is an objection from a maintainer.

**Comment by xhochy** [comment]
… and not to wait on CI.

**Comment by talagluck** [comment]
@xhochy, I’m sorry about that, I am new to the process and didn’t mean offense. Thank you for helping me work through it. I'm taking steps to make sure I don't make these mistakes in the future.

**Pull request merged**
